# Generated by Django 5.0 on 2025-02-12 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0002_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractorabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('workimage1', models.ImageField(blank=True, null=True, upload_to='')),
                ('workimage2', models.ImageField(blank=True, null=True, upload_to='')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urban.contractor')),
            ],
        ),
    ]
