# Generated by Django 5.0 on 2025-02-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0003_contractorabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
