# Generated by Django 5.1.4 on 2025-02-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0004_alter_contractor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
