# Generated by Django 5.1.4 on 2025-02-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0005_worker_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message from the consumer to the contractor')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created')),
                ('is_read', models.BooleanField(default=False, help_text='Flag to indicate whether the notification has been read by the contractor')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urban.consumer')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urban.contractor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
