# Generated by Django 5.1.4 on 2025-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0007_alter_worker_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='profile_pic',
            field=models.FileField(blank=True, default='profile_files/default.pdf', null=True, upload_to='profile_files'),
        ),
    ]
