# Generated by Django 5.1.4 on 2025-02-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0008_alter_worker_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urban.consumer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urban.services')),
            ],
            options={
                'unique_together': {('consumer', 'service')},
            },
        ),
    ]
