# Generated by Django 5.1.4 on 2025-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0010_alter_booking_mobile_alter_contractor_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
