# Generated by Django 5.1.4 on 2025-02-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0011_consumer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
